from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('football/', views.football_index, name='footballindex'),
    path('basketball/', views.basketball_index, name='basketballindex'),
    path('baseball/', views.baseball_index, name='baseballindex'),
    path('mma/', views.mma_index, name='mmaindex'),
    path('soccer/', views.soccer_index, name='soccerindex'),
    path('hockey/', views.hockey_index, name='hockeyindex'),
    path('football/<int:football_id>/', views.football_detail, name='footballdetail'),
    path('basketball/<int:basketball_id>/', views.basketball_detail, name='basketballdetail'),
    path('baseball/<int:baseball_id>/', views.baseball_detail, name='baseballdetail'),
    path('mma/<int:mma_id>/', views.mma_detail, name='mmadetail'),
    path('soccer/<int:soccer_id>/', views.soccer_detail, name='soccerdetail'),
    path('hockey/<int:hockey_id>/', views.hockey_detail, name='hockeydetail'),
    path('football/create/', views.FootballCreate.as_view(), name='football_create'),
    path('baseball/create/', views.BaseballCreate.as_view(), name='baseball_create'),
    path('basketball/create/', views.BasketballCreate.as_view(), name='basketball_create'),
    path('hockey/create/', views.HockeyCreate.as_view(), name='hockey_create'),
    path('mma/create/', views.MmaCreate.as_view(), name='mma_create'),
    path('soccer/create/', views.SoccerCreate.as_view(), name='soccer_create'),
    path('football/<int:pk>/update/', views.FootballUpdate.as_view(), name='football_update'),
    path('baseball/<int:pk>/update/', views.BaseballUpdate.as_view(), name='baseball_update'),
    path('basketball/<int:pk>/update/', views.BasketballUpdate.as_view(), name='basketball_update'),
    path('hockey/<int:pk>/update/', views.HockeyUpdate.as_view(), name='hockey_update'),
    path('mma/<int:pk>/update/', views.MmaUpdate.as_view(), name='mma_update'),
    path('soccer/<int:pk>/update/', views.SoccerUpdate.as_view(), name='soccer_update'),
    path('football/<int:pk>/delete/', views.FootballDelete.as_view(), name='football_delete'),
    path('baseball/<int:pk>/delete/', views.BaseballDelete.as_view(), name='baseball_delete'),
    path('basketball/<int:pk>/delete/', views.BasketballDelete.as_view(), name='basketball_delete'),
    path('hockey/<int:pk>/delete/', views.HockeyDelete.as_view(), name='hockey_delete'),
    path('mma/<int:pk>/delete/', views.MmaDelete.as_view(), name='mma_delete'),
    path('soccer/<int:pk>/delete/', views.SoccerDelete.as_view(), name='soccer_delete'),
]
